### ISSUE TITLE
Error "sorted_column" not found in get_independent_relevant_phenotypes_server function

### ISSUE THREAD

**Issue by sciOmics** [SciOmicsLab/PhenoComb#5]
> get_independent_relevant_phenotypes_server("/Users/david/Downloads/15400_CheckPoint_Ligand/Week_0_Results",
+                                            "/Users/david/Downloads/15400_CheckPoint_Ligand/Thresholds.csv",
+                                            "/Users/david/Downloads/15400_CheckPoint_Ligand/Sample_Info.csv",
+                                            max_pval = 0.05,
+                                            n_phenotypes = 10000,
+                                            min_confidence = 0.1,
+                                            n_threads = 22,
+                                            verbose = TRUE)
[22/03/07 21:35:47] Starting log...
[22/03/07 21:35:47] Reading data...
Error in `[.data.frame`(x, i, j) : object '..sorted_column' not found

**Comment by pauloburke** [comment]
Fixing it in 29d08f3d4107db9677a54402a13bd467fc7b3a76

please check if it's working now.

**Comment by pauloburke** [comment]
The fixing gave me errors on other functions because of adding data.table NAMESPACE. Will fix that soon.

**Comment by pauloburke** [comment]
Fixed on bb4519c7158ddea2198f01b1d5a7105748bae747

Please let me know if it's running smoothly now...
