### ISSUE TITLE
Clarity on defining Marker States; statistical tests and interpretation

### ISSUE THREAD

**Issue by amatoc** [SciOmicsLab/PhenoComb#8]
I ran the demo data without any problems.  Could I have some some clarity on how effect size is calculated and how to interpret it?  In calculating statistical relevant phenotypes (comparing  the blood, g1, and tumor samples, g2), the values returned for effect size were  1 or -1.    In this case, a value of 1 indicates that the indicated phenotype is (more) prevalent in the blood, while a -1 suggests the phenotype is prevalent in the tumor.  

Related to Marker States:  I'm unsure of the difference between dropping the marker (indicated with a -1) and it being negative (indicated with 0).  Why wouldn't negative markers be dropped as well?

**Comment by pauloburke** [comment]
Regarding the effect size. The value can range from -1 to 1. It is related to ranking process of the Mann-Whitney U test. The original value of the test is the number of samples in group 1 that are greater than group 2 minus the number of samples in group 2 that are greater than samples in group 1. I normalize this value to be in the -1:1 range. So a value closer to one means that more samples in group one have a higher frequency than group 2. Values closer to -1 means the opposite.

**Comment by pauloburke** [comment]
Regarding marker states, consider a set with two markers A and B. The following encodings gives you an example:

0 1 = A-B+
-1 1 = B+

Does that make sense?
